version: '3'

services:
    api:
        image: 'api'
        container_name: 'api_server'
        build: './packages/api/'
        ports:
            - '8080:3000'
        environment:
            - NODE_ENV=development
        # volumes:
        #     - notused:/api/node_modules
        #     - './packages/api/:/api'
        restart: 'always'
    adminClient:
        image: 'admin_client'
        container_name: 'admin_client'
        environment:
            - WATCHPACK_POLLING=true
        # volumes:
        #     - notused:/adminClient/node_modules
        #     - './packages/clients/adminClient/:/adminClient'
        ports:
            - '8880:1338'
        build: './packages/clients/adminClient/'
    userClient:
        image: 'user_client'
        container_name: 'user_client'
        environment:
            - WATCHPACK_POLLING=true
        # volumes:
        #     - notused:/userClient/node_modules
        #     - './packages/clients/userClient/:/userClient'
        ports:
            - '8889:1339'
        build: './packages/clients/userClient/'
    userMobileClient:
        image: 'user_mobile_client'
        container_name: 'user_mobile_client'
        build: './packages/clients/userMobileClient'
        environment:
            - NODE_ENV=development
        tty: true
        ports:
            - '19006:19006'
            - '19001:19001'
            - '19002:19002'
        volumes:
            - './packages/clients/userMobileClient/app:/opt/app'
            - notused:/opt/userMobileClient/app/node_modules
        healthcheck:
            disable: true

volumes:
    notused:
