-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 13:43:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vteams
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vteams` ;

-- -----------------------------------------------------
-- Schema vteams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vteams` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `vteams` ;

-- -----------------------------------------------------
-- Table `vteams`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(100) NULL,
  `register_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `social_security` VARCHAR(45) NULL,
  `enabled` TINYINT(1) NULL DEFAULT 1,
  `credit` FLOAT NULL DEFAULT 0,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`city` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`city` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`scooter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`scooter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`scooter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `charge` INT NOT NULL DEFAULT 100,
  `last_serviced` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `first_used` TIMESTAMP NULL,
  `distance_traveled` FLOAT NULL DEFAULT 0,
  `last_position` POINT NULL,
  `is_charging` TINYINT(1) NOT NULL DEFAULT 0,
  `city_id` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `scooter_city_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `scooter_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `vteams`.`city` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`parking_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`parking_zone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`parking_zone` (
  `id` VARCHAR(20) NOT NULL,
  `city_id` VARCHAR(20) NULL,
  `area` POLYGON NULL,
  PRIMARY KEY (`id`),
  INDEX `parking_zone_city_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `parking_zone_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `vteams`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`charging_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`charging_zone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`charging_zone` (
  `id` VARCHAR(20) NOT NULL,
  `parking_zone_id` VARCHAR(20) NULL,
  `area` POLYGON NULL,
  PRIMARY KEY (`id`),
  INDEX `charging_zone_parking_zone_idx` (`parking_zone_id` ASC) VISIBLE,
  CONSTRAINT `charging_zone_parking_zone`
    FOREIGN KEY (`parking_zone_id`)
    REFERENCES `vteams`.`parking_zone` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`charging_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`charging_station` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`charging_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charging_zone_id` VARCHAR(20) NOT NULL,
  `position` POINT NOT NULL,
  `occupied` TINYINT(1) NOT NULL DEFAULT 0,
  `scooter_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `charging_station_charging_zone_idx` (`charging_zone_id` ASC) VISIBLE,
  INDEX `charging_station_bike_idx` (`scooter_id` ASC) VISIBLE,
  CONSTRAINT `charging_station_charging_zone`
    FOREIGN KEY (`charging_zone_id`)
    REFERENCES `vteams`.`charging_zone` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `charging_station_scooter`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `vteams`.`scooter` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`trip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `scooter_id` INT NULL,
  `distance` FLOAT NULL DEFAULT 0,
  `completed` TINYINT(1) NULL DEFAULT 0,
  `start_position` POINT NOT NULL,
  `stop_position` POINT NULL,
  `start_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `stop_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `trip_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `trip_bike_idx` (`scooter_id` ASC) VISIBLE,
  CONSTRAINT `trip_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vteams`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `trip_scooter`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `vteams`.`scooter` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`invoice` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `payed` TIMESTAMP NULL,
  `amount` FLOAT NOT NULL,
  `billed` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `invoice_trip_idx` (`trip_id` ASC) VISIBLE,
  CONSTRAINT `invoice_trip`
    FOREIGN KEY (`trip_id`)
    REFERENCES `vteams`.`trip` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`scooter_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`scooter_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`scooter_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scooter_id` INT NULL,
  `speed` INT NULL,
  `position` POINT NULL,
  `status` VARCHAR(20) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `charge` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `bike_log_bike_idx` (`scooter_id` ASC) VISIBLE,
  CONSTRAINT `scooter_log_scooter`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `vteams`.`scooter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vteams`.`maintenance_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vteams`.`maintenance_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vteams`.`maintenance_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scooter_id` INT NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `event` VARCHAR(100) NULL,
  `invoked_by` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `maintenance_log_bike_idx` (`scooter_id` ASC) VISIBLE,
  CONSTRAINT `maintenance_log_scooter`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `vteams`.`scooter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
USE `vteams`;

DELIMITER $$

USE `vteams`$$
DROP TRIGGER IF EXISTS `vteams`.`trip_AFTER_UPDATE` $$
SHOW WARNINGS$$
USE `vteams`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vteams`.`trip_AFTER_UPDATE` AFTER UPDATE ON `trip` FOR EACH ROW
BEGIN
	IF NEW.stop_position IS NOT NULL THEN
		SET @amount = TIMESTAMPDIFF(MINUTE,NEW.start_time, NEW.stop_time) * 3 + 10;
			INSERT INTO invoice (trip_id, amount)
			VALUES (NEW.id, @amount);
	END IF;
END$$

SHOW WARNINGS$$

USE `vteams`$$
DROP TRIGGER IF EXISTS `vteams`.`scooter_log_AFTER_INSERT` $$
SHOW WARNINGS$$
USE `vteams`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vteams`.`scooter_log_AFTER_INSERT` AFTER INSERT ON `scooter_log` FOR EACH ROW
BEGIN
UPDATE scooter
SET last_position = NEW.position,
	charge		  = NEW.charge,
    distance_traveled = distance_traveled + (NEW.speed * (1/60))
WHERE id = NEW.scooter_id;
END$$

SHOW WARNINGS$$

USE `vteams`$$
DROP TRIGGER IF EXISTS `vteams`.`maintenance_log_AFTER_INSERT` $$
SHOW WARNINGS$$
USE `vteams`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vteams`.`maintenance_log_AFTER_INSERT` AFTER INSERT ON `maintenance_log` FOR EACH ROW
BEGIN
	IF NEW.invoked_by = 'service' THEN
		UPDATE scooter
        SET scooter.last_serviced = CURRENT_TIMESTAMP()
        WHERE scooter.id = NEW.scooter_id;
	END IF;
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
