name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install modules
      run: npm install
    - name: Run Prettier
      run: npx prettier --write .
    - name: Run ESLint
      run: npx eslint . --fix
